--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Henry12960/CustomPVP
build-by-default: true
branches:
- main
projects:
  CustomPVP:
    path: ""
    icon: "CustomPVP.png"
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
...