name: CustomPVP
main: HenryDM\CustomPVP\Main
api: [4.0.0]
version: 2.0.0-dev
author: HenryDM
description: Simple Plugin To Customize PvP In Your Server
website: https://github.com/Henry12960
softdepend: 
  - BedrockEconomy
  - EconomyAPI