name: CustomPVP
main: HenryDM\CustomPVP\Main
api: [4.0.0]
version: 3.1.0
authors: [HenryDM, Ihsan48, FernanACM, PetterLight, CaioVox, Estern01, TacoError] 
<<<<<<< HEAD
description: Aadvanced Plugin To Customize Your PvP Server
=======
description: Advanced Plugin To Customize Your PvP Server
>>>>>>> 9de65a0e2935016e5ce5993f9edb6b115fe41811
softdepend: 
  - BedrockEconomy
  - EconomyAPI
