name: CustomPVP
main: HenryDM\CustomPVP\Main
api: [4.0.0]
version: 4.0.0
author: [Ihsan48, FernanACM, PetterLight, CaioVox, Estern01, TacoError] 
description: Advanced Plugin to Customize your pvp server
website: https://github.com/Henry12960

softdepend: 
  - BedrockEconomy
  - EconomyAPI