#   _____          _                  _______      _______  
#  / ____|        | |                |  __ \ \    / /  __ \ 
# | |    _   _ ___| |_ ___  _ __ ___ | |__) \ \  / /| |__) |
# | |   | | | / __| __/ _ \| '_ ` _ \|  ___/ \ \/ / |  ___/ 
# | |___| |_| \__ \ || (_) | | | | | | |      \  /  | |     
#  \_____\__,_|___/\__\___/|_| |_| |_|_|       \/   |_|     
#                                                                                                                     
# A advanced plugin to customize pvp on your server 
# Any bugs that come up please report on github: https://github.com/Henry12960/CustomPVP/issues
# Give suggestions: https://github.com/Henry12960/CustomPVP/issues/2
# Plugin Wiki: https://github.com/Henry12960/CustomPVP/wiki

# Settings:

# Kill Message
kill-message: "§c{victim} was killed by {killer}!"
# Use true to activate
message: true

# PvP cooldown
cooldown-time: 1.6
# Use true to activate
cooldown: true
# Info: time in milliseconds for the player to hit another player again

# PvP knockback
knockback-level: 0.50
# Use true to activate
knockback: true
# Info: DO NOT SWITCH TO MORE THAN 5.0 SUBJECT TO BUGS!

# Restore Health on Kill player
# Use true to activate 
restore-helth: true
# Worlds
restore-worlds: 
  - Arena #Example
  - KitPvP #Example
# Soup PvP
# Use true to activate
soup-pvp: true
# Regenerate Level
regenerate-level: 5
# Soup ID
# Use 282 to Mushroom Stew and 459 the Beet Stew
soup-id: 282
# Soup Message
soup-message: "§aLife successfully restored."
# Soup World's
soup-worlds:
  - Arena #Example
  - SoupArena #Example
# Leeching Mode
# Use true to activate
leeching-mode: true
# Worlds
leeching-worlds: [KitPvP, Arena] # Examples
# Leeching Level
leeching-level: 5

# Death Kick
# Set to true to enable this feature
death-kick: false 

# If you set to true add Worl's when this feature Work's
kick-worlds:
  - KickArena #Example
  - ArenaKick #Example

# If you set to true add on Kick Message
# You can use Minecraft Color codes
kick-message: "Oof! You Death"

# PingKick
pingkick-enable: true

pingkick-max: 400

# Kill Particles
# Set to true for enable this feature 
kill-particles: false

# If you set to true add world's when this feature work's 
particle-worlds: 
  - Arena #Example
  - KitPvP #Example 

# KillMoney
# Set to false if you want to disable the KillMoney feature
# Default: true
killmoney-enable: true

# If you set to true add worlds where this feature works
killmoney-world:
  - world # Example
  - survival # Example

# KillMoney Price
killmoney-price: 1000

# KillMoney Reduce feature
# Set to true to make players money reduce when killed
killmoney-reduce: true

# KillDeath Sound
# Set to false if you want to disable the KillMoney feature
# Default: true

killsound-enable: true

# If you set to true add worlds where this feature works
killsound-worlds:
  - pvp # Example
  - survival # Example

# KillDeath Sound Name

killsound-soundname: "random.explode"

# KillReward
# Set to false if you want to disable the KillMoney feature
# Default: true
killrewards-enable: true

# If you set to true add worlds where this feature works
killrewards-worlds:
  - pvp
  - survival

# Reward Item

killrewards-items:

  - slots: 0
    id: 265
    damage: 0
    count: 1
    name: KillReward


# AntiFlight

# Set to false if you want to disable the AntiPvpFlight feature
# Default: true
antipvpflight: true
# If you set to true add world's where this feature works 

antiflight-worlds: 
  - world # Example
  - arena # Example

# Particles List 
# Attention: only set to true ONE

critical-particle: true
explode-particle: false
flame-particle: false
heart-particle: false
lava-particle: false
nether-particle: false
redstone-particle: false
snow-particle: false

# Death Effects
# Use "true" or "false" to enable/disable this mode
death-effects: true
# Worlds where this mode is supported
effect-worlds:
  - "world" # Examnple
  - "ZonePvP" #Example
# Effect
effect:
  id: 1 # Speed effect
  duration: 30 # Duration effect
  level: 1 # Maximum level 4
  particle: true # Particle effect
# Here's a list of all available effects with their IDs

# ABSORPTION = 22
# BLINDNESS = 15
# CONDUIT_POWER = 26
# CONFUSION = 9
# DAMAGE_RESISTANCE = 11
# FATAL_POISON = 25
# FATIGUE = 4
# FIRE_RESISTANCE = 12
# HARMING = 7
# HASTE = 3
# HEALING = 6
# HEALTH_BOOST = 21
# HUNGER = 17
# INSTANT_DAMAGE = 7
# INSTANT_HEALTH = 6
# INVISIBILITY = 14
# JUMP = 8
# JUMP_BOOST = 8
# LEVITATION = 24
# MINING_FATIGUE = 4
# NAUSEA = 9
# NIGHT_VISION = 16
# POISON = 19
# REGENERATION = 10
# RESISTANCE = 11
# SATURATION = 23
# SLOWNESS = 2
# SPEED = 1
# STRENGTH = 5
# WATER_BREATHING = 13
# WEAKNESS = 18
# WITHER = 20