#   _____          _                  _______      _______  
#  / ____|        | |                |  __ \ \    / /  __ \ 
# | |    _   _ ___| |_ ___  _ __ ___ | |__) \ \  / /| |__) |
# | |   | | | / __| __/ _ \| '_ ` _ \|  ___/ \ \/ / |  ___/ 
# | |___| |_| \__ \ || (_) | | | | | | |      \  /  | |     
#  \_____\__,_|___/\__\___/|_| |_| |_|_|       \/   |_|     
#                                                                                                                     
# A simple plugin to customize pvp on your server 
# any bugs that come up please report on github: https://github.com/Henry12960

# Settings:

# Kill Message
kill-message: "§c{victim} was killed by {killer}!"

# PvP cooldown
cooldown-time: 1.6
# Use true to activate
cooldown: true
# Info: time in milliseconds for the player to hit another player again

# PvP knockback
knockback-level: 0.50
# Use true to activate
knockback: true
# Info: DO NOT SWITCH TO MORE THAN 5.0 SUBJECT TO BUGS!

# Restore Health on Kill player
# Use true to activate 
restore-helth: true
# Worlds
restore-worlds: [KitPvP, Arena] # Examples

# Soup PvP
regenerate-level: 5
# Soup ID
soup-id: 459
# Soup Message
soup-message: "§aLife successfully restored."
# Use true to activate
soup-pvp: true

# Leeching Mode
# Use true to activate
leeching-mode: true
# Worlds
leeching-worlds: [KitPvP, Arena] # Examples
# Regenerate Level
regenerate-level: 5
