---
# ===================
#     CUSTOM PVP
# ===================
# 1. Advanced plugin to customize your pvp server
# 2. Plugin Wiki: https://github.com/Henry12960/CustomPVP/wiki
# 3. You find a problem? Open a issue: https://github.com/Henry12960/CustomPVP/issues/new
# 4. Star project for more: https://github.com/Henry12960/CustomPVP
# 5. Rate plugin on poggit: https://poggit.pmmp.io/p/CustomPVP
# 6. All Addons are disabled, you can enable change false to true!
# 7. Activated all addons can cause errors and extreme ram consume, i'm not responsible for this!
# 8. Thanks for everything! - By Henry Thierry [HenryDM]

# ===================
#   Plugin Version
# ===================
# 1º Only for internal use!

config-version: "4.0.0"

# ===================
#   Attack Cooldown
# ===================
# 1º This addon modify player attack cooldown!
# 2º Max Cooldown = undefined  

attack-cooldown: false
attack-cooldown-time: 2
attack-cooldown-worlds: ["CooldownArena", "CooldownWorld"]

# ===================
#   Health Restore
# ===================
# 1º This addon add a event that when player die, other player restore all life

health-restore: false
health-restore-worlds: ["RestoreArena", "RestoreWorld"]

# ===================
#      KnockBack
# ===================
# 1º This addon modify player attack knockback!
# 2º Recomended Max KnockBack = 5

pvp-knockback: false
pvp-knockback-level: 2
pvp-knockback-worlds: ["KnockbackArena", "KnockbackWorld"]

# ===================
#    Leeching Mode
# ===================
# 1º This addon add a custom leeching mode create by HenryDM!
# 2º If you don't know how work's this, check plugin wiki! 
# 3º https://github.com/Henry12960/CustomPVP/wiki
# 4º Leeching-level = hearts

leeching-mode: false
leeching-level: 5
pvp-knockback-worlds: ["LeechingArena", "LeechingWorld"]

# ===================
#      Soup PvP
# ===================
# 1º This addon add a famous soup pvp mode!
# 2º If you set "soup-consume-message-type-popup" to true, messages are displayed in popup format, else, in message format!
# 3º Set to true "soup-message" if you want display soup consume message
# 4º You can use minecraft color codes in "soup-message"!
# 5º "soup-id" = Mushroom Stew (282), you can use too Beetroot Soup id (436)

soup-pvp: false
soup-hearts: 3
soup-id: 282
soup-consume-message: false
soup-message-type-popup: false
soup-message: "§a+3 hearts"
soup-pvp-worlds: ["SoupArena", "SoupWorld"]

# ===================
#     Death Clear
# ===================
# 1º This addon clear player inventory when player dies!
# 2º "death-clear-modes" = all or armor

death-clear: false
death-clear-mode: "all"
death-clear-worlds: ["ClearArena", "ClearWorld"]

# ===================
#    Death Effects
# ===================
# 1º This addon add effects to player on death

death-effects: false 
effect-worlds: ["EffectArnea", "EffectWorld"]

effect:
  id: 1 # Add effect id here
  duration: 30 # Add effect duration here
  level: 1 # Add effect level here
  particles: false # Set to true to show particles effects

# ===================
#     Death Kick
# ===================
# 1º This addon add a event that when player dies his is kicked from server!
# 2º You can use minecraft color codes in "death-kick-message"

death-kick: false
death-kick-message: "§cSorry! You died"
death-kick-worlds: ["KickArena", "KickWorld"]

# ===================
#    Death Message
# ===================
# 1º This addon add a event that change player message when his dies!
# 2º You can use minecraft color codes in "death-message-alert"
# 3º You can use {victim} and {killer} in "death-message-alert"

death-message: false
death-message-alert: "§c{victim} has be killed by {killer}"

# ===================
#     Kill Money
# ===================
# 1º This addon add a popular kill money event!
# 2º If "reduce-money" is active when player dies he will lose money!

kill-money: false
reduce-money: false
money-value: 10 
kill-money-worlds: ["MoneyArena", "MoneyWorld"]

# ===================
#     Kill EXP
# ===================
# 1º This addon add exp to player when kill another!
# 2º Recomended Max "kill-exp-level" = 3

kill-exp: false
kill-exp-level: 2
kill-exp-worlds: ["ExpArena", "ExpWorld"]

# ===================
#    Kill Particles
# ===================
# 1º This addon add a particle when player dies!
# 2º Only define to true one particle!

kill-particle: false
kill-particles-worlds: ["ParticleArena", "ParticleWorld"]

critical-particle: true
explode-particle: false
flame-particle: false
heart-particle: false
lava-particle: false
portal-particle: false
redstone-particle: false
snow-particle: false

# ===================
#     Kill Reward
# ===================
# 1º This addon add a reward when player kill another!
# 2º Invalid item id cause plugin error!

kill-rewards: false
kill-rewards-worlds: ["RewardArena", "RewardWorld"]

rewards-items:

  - slots: 0 # Item slot
    id: 265 # Item ID
    damage: 0 # Item damage
    count: 1 # Item value
    name: KillReward # Item name

# ===================
#     Kill Sound
# ===================
# 1º This addon add a sound when player kill another!
# 2º Invalid sound name cause plugin error!
# 3º Soun Wiki: https://minecraft.fandom.com/wiki/Sounds.json/Bedrock_Edition_values

kill-sound: false
kill-sound-name: "random-orb"
kill-sound-worlds: ["SoundArena", "SoundWorld"]

# ===================
#    Anti Flight
# ===================
# 1º This addon disable player fly on pvp damage!

anti-flight: false
anti-flight-worlds: ["AntiFlightArena", "AntiFlightWorld"]

# ===================
#      Anti PvP
# ===================
# 1º This addon disable player pvp in certains worlds!

anti-pvp: false
anti-pvp-worlds: ["AntiPvPArena", "AntiPvPWorld"]

# ===================
#     Ping Kick
# ===================
# 1º This addon kick player from the server if their ping is >= "ping-kick-max-ping"
# 2º You can use minecraft color codes in "ping-kick-message"

ping-kick: false
ping-kick-max-ping: 120
ping-kick-message: "§eYour ping has exceeded 120ms"
ping-kick-worlds: ["PingKickArena", "PingKickWorld"]
...