Oi#   _____          _                  _______      _______  
#  / ____|        | |                |  __ \ \    / /  __ \ 
# | |    _   _ ___| |_ ___  _ __ ___ | |__) \ \  / /| |__) |
# | |   | | | / __| __/ _ \| '_ ` _ \|  ___/ \ \/ / |  ___/ 
# | |___| |_| \__ \ || (_) | | | | | | |      \  /  | |     
#  \_____\__,_|___/\__\___/|_| |_| |_|_|       \/   |_|     
#                                                                                                                     
# A advanced plugin to customize pvp on your server 
# Any bugs that come up please report on github: https://github.com/Henry12960
# Give suggestions: https://github.com/Henry12960/CustomPVP/issues/2
# Plugin Wiki: https://github.com/Henry12960/CustomPVP/wiki

# Settings:

# Kill Message
kill-message: "§c{victim} was killed by {killer}!"
# Use true to activate
message: true

# PvP cooldown
cooldown-time: 1.6
# Use true to activate
cooldown: true
# Info: time in milliseconds for the player to hit another player again

# PvP knockback
knockback-level: 0.50
# Use true to activate
knockback: true
# Info: DO NOT SWITCH TO MORE THAN 5.0 SUBJECT TO BUGS!

# Restore Health on Kill player
# Use true to activate 
restore-helth: true
# Worlds
restore-worlds: 
  - Arena #Example
  - KitPvP #Example

# Soup PvP
# Use true to activate
soup-pvp: true
# Regenerate Level
regenerate-level: 5
# Soup ID
# Use 282 to Mushroom Stew and 459 the Beet Stew
soup-id: 282
# Soup Message
soup-message: "§aLife successfully restored."
# Soup World's
soup-worlds:
  - Arena #Example
  - SoupArena #Example                                
                                                       
# Leeching Mode
# Use true to activate
leeching-mode: true
# Worlds
leeching-worlds: [KitPvP, Arena] # Examples
# Leeching Level
leeching-level: 5

# Kill Particles
# Set to true for enable this feature 
kill-particles: false

# If you set to true add world's when this feature work's 
particle-worlds: 
  - Arena #Example
  - KitPvP #Example 

# Kill Sound
# Set to true enable this Features
kill-sound: false

# KillMoney

# Set to false if you want to disable the KillMoney feature
killmoney-enable: true

# If you set to true add world's when this feature work's 
killmoney-world:
  - world # Example
  - survival # Example

# KillMoney Price
killmoney-price: 1000

# KillMoney Reduce feature
# Set to true to make players money reduce when killed
killmoney-reduce: true

# Particles List 
# Attention: only set to true ONE

critical-particle: true
explode-particle: false
flame-particle: false
heart-particle: false
lava-particle: false
nether-particle: false
redstone-particle: false
snow-particle: false

# Sounds List
# Attention: only set to true ONE

anvil-sound: false
