---
#   _____          _                  _______      _______  
#  / ____|        | |                |  __ \ \    / /  __ \ 
# | |    _   _ ___| |_ ___  _ __ ___ | |__) \ \  / /| |__) |
# | |   | | | / __| __/ _ \| '_ ` _ \|  ___/ \ \/ / |  ___/ 
# | |___| |_| \__ \ || (_) | | | | | | |      \  /  | |     
#  \_____\__,_|___/\__\___/|_| |_| |_|_|       \/   |_|     
#                                                                                                                     
# A advanced plugin to customize pvp on your server 
# Any bugs that come up please report on github: https://github.com/Henry12960/CustomPVP/issues
# Give suggestions: https://github.com/Henry12960/CustomPVP/issues/2
# Plugin Wiki: https://github.com/Henry12960/CustomPVP/wiki
# Minecraft Sounds Wiki: https://minecraft.fandom.com/wiki/Sounds.json/Bedrock_Edition_values
# All Add-ons are disable, set to "true" to enable!

# =====================
#    AntiFlight PvP
# =====================
# Info: This feature allow you to disable players fly on pvp!

anti-flight: false 

antiflight-worlds: 
  - AntiFlightArena # Example

# =====================
#    AntiPvP Worlds
# =====================
# Info: This feature allow you to disable pvp on certains worlds!

anti-pvp: false 
blocked-pvp-messages: "§cPvp is disabled for this world!"

block-pvp-worlds: 
  - Lobby # Example 
  
# =====================
#    Attack Cooldown
# =====================
# Info: This feature allow you to set pvp cooldown!

attack-cooldown: false 

cooldown-worlds:
  - CooldownArena # Example

# =====================
#     Death Effects
# =====================
# Info: This feature allow you to add Player's death effects

death-effects: false 

effects-worlds: 
  - EffectArena - Example

effect:
  id: 1 # Add here effect id
  duration: 30 # Add here effect duration
  level: 1 # Add here effect level
  particles: false # Set to true to show particles effects

# =====================
#      Death Kick
# =====================
# Info: This feature allows you to kick the player when he dies

death-kick: false 
death-kick-message: "§cOof! You Death"

death-kick-worlds: 
  - KickArena # Example

# =====================
#    HealthRestore
# =====================
# Info: This feature allow you to recover all heart on kill player  

heath-restore: false 

restore-worlds:
  - HealthArena # Example

# =====================
#      KillMoney
# =====================
# Info: This feature allows you to give money to the player when killing another

kill-money: false 
money-reduce: false # if active when player dies he will lose money
money-value: 10 

money-worlds: 
  - MoneyArena # Example

# =====================
#    Kill Particles
# =====================
# Info: This feature allows you to add particles on kill players (liked Hypixel)

kill-particles: false 

particles-worlds: 
  - ParticleArena # Example

critical-particle: true
explode-particle: false
flame-particle: false
heart-particle: false
lava-particle: false
portal-particle: false
redstone-particle: false
snow-particle: false

# =====================
#      KillReward
# =====================
# Info: This feature allows you to give rewards (items) when killing players

kill-rewards: false 

rewards-worlds: 
  - RewardsArena # Example
  
rewards-items:

  - slots: 0 # Item slot
    id: 265 # Item ID
    damage: 0 # Item damage
    count: 1 # Item value
    name: KillReward # Item name

# =====================
#      KillSound
# =====================
# Info: This feature allows you to add sounds when killing players

kill-sound: false 
sound-name: "random.explode" # Example

sound-worlds:
  - SoundArena # Example

# =====================
#    PvP KnockBack
# =====================
# Info: This feature allows you to modify pvp Knockback

pvp-knockback: false
knockback-level: 0.50

knockback-worlds: 
  - KnobackArena # Example

# =====================
#    Leeching Mode
# =====================
# Info: This feature allows you to add custom leeching mode (Check Plugin Wiki)

leeching-mode: false 
leeching-level: 3 # Max = 10

leeching-worlds: 
  - LeechingArena

# =====================
#     PvP Messages
# =====================
# Info: This feature allows you to custom pvp messages
# Info 2: Use {killer} to add Killer Name and {victim} to add victim name

pvp-messages: false 
kill-message: "§c[-] §6{victim} §cwas killed by §6{killer}" # Example

# =====================
#       Ping Kick
# =====================
# Info: This feature allows you to remove lag Player's from the server

ping-kick: false 
ping-kick-max: 500 
ping-kick-message: "§cSorry but your ping was so high"

ping-kick-worlds:
  - PingKickArena - Example

# =====================
#      Soup PvP
# =====================
# Info: This feature allows you to add Soup PvP in your server

soup-pvp: false 
soup-id: 282
soup-level: 5
soup-message: "§a+5 Hearts" 

soup-worlds: 
  - SoupPvP # Example
...